apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.25.4
controlPlaneEndpoint: "{{ groups['controllers'][0] }}:6443"
networking:
  podSubnet: 10.25.0.0/16
apiServer:
  certSANs:
    {% for host in groups['controllers'] -%}
    - {{ host }}
    - {{ hostvars[host]['ansible_host'] }}
    - {{ hostvars[host]['internal_host'] }}
    {% endfor %}
